services:
  - type: web
    name: biomassrecords
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
      - key: VITE_API_KEY
        sync: false
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
